version: '3.8'

services:
  #Application Image
  java_app_batch:
    container_name: java_app_batch
    image: java_spring_batch
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db_batch:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

    depends_on:
      - java_db_batch
  #Database Image
  java_db_batch:
    container_name: java_db_batch
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}